import { mkdir, copyFile, cp, rm, readFile, writeFile } from 'node:fs/promises';
import { build } from 'esbuild';
await rm('dist', { recursive: true, force: true });
await mkdir('dist/server', { recursive: true }); await mkdir('dist/client', { recursive: true }); await mkdir('dist/.openai', { recursive: true });
await copyFile('static/index.html', 'dist/client/index.html');
await writeFile('dist/client/style.css', (await readFile('app/globals.css', 'utf8')) + '\n' + (await readFile('static/production.css', 'utf8')));
await copyFile('.openai/hosting.json', 'dist/.openai/hosting.json');
await cp('.openai/drizzle', 'dist/.openai/drizzle', { recursive: true });
await build({ entryPoints: ['static/app.js'], outfile: 'dist/client/app.js', bundle: true, format: 'esm', platform: 'browser', target: 'es2022', minify: true });
await build({ entryPoints: ['worker/index.ts'], outfile: 'dist/server/index.js', bundle: true, format: 'esm', platform: 'browser', target: 'es2022', minify: true });
console.log('Nutrition app built successfully.');
